/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppleIcon: typeof import('./src/components/icons/AppleIcon.vue')['default']
    EyeOffIcon: typeof import('./src/components/icons/EyeOffIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    USFlagIcon: typeof import('./src/components/icons/USFlagIcon.vue')['default']
    VanIcon: typeof import('vant/es')['Icon']
    YoutubeIcon: typeof import('./src/components/icons/YoutubeIcon.vue')['default']
  }
}
